/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.42
 * Generated at: 2025-08-05 13:56:25 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import com.javarush.zhdanovskikh.cmd.QuestData;

public final class quest_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/WEB-INF/lib/jakarta.servlet.jsp.jstl-3.0.1.jar", Long.valueOf(1753285388056L));
    _jspx_dependants.put("/WEB-INF/head.jsp", Long.valueOf(1753525143183L));
    _jspx_dependants.put("jar:file:/C:/Users/Phantom_Us/.m2/repository/org/glassfish/web/jakarta.servlet.jsp.jstl/3.0.1/jakarta.servlet.jsp.jstl-3.0.1.jar!/META-INF/c-1_2.tld", Long.valueOf(1664435478000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(2);
    _jspx_imports_classes.add("com.javarush.zhdanovskikh.cmd.QuestData");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("    <title>Project Quest</title>\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css\" rel=\"stylesheet\"\n");
      out.write("          integrity=\"sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH\" crossorigin=\"anonymous\">\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js\"\n");
      out.write("            integrity=\"sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz\"\n");
      out.write("            crossorigin=\"anonymous\"></script>\n");
      out.write("</head>");
      out.write("\n");
      out.write("<html>\n");
      out.write("\n");
      out.write("<body onload=\"displayText()\">\n");
      out.write("<form method=\"post\" >\n");
 QuestData quest; 
      out.write('\n');
quest = (QuestData) request.getAttribute("questData");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<h1>");
      out.print("Проект квест");
      out.write("\n");
      out.write("\n");
      out.write("</h1>\n");
      out.write("    <table id=\"questTbl\">\n");
      out.write("        <tr>\n");
      out.write("            <td></td>\n");
      out.write("        </tr>\n");
      out.write("        <tr>\n");
      out.write("            <td> <br> Ваши действия:</td>\n");
      out.write("        </tr>\n");
      out.write("    </table>\n");
      out.write("    <button type=\"submit\" name=\"Btn1\" id=\"Btn1\" >\n");
      out.write("        Button_1\n");
      out.write("    </button>\n");
      out.write("    <button type=\"submit\" name=\"Btn2\" id=\"Btn2\" >\n");
      out.write("        Button_2\n");
      out.write("    </button>\n");
      out.write("    <a href=\"/\" id=\"backLnk\" >Go back </a>\n");
      out.write("\n");
      out.write("<script>\n");
      out.write("var isQuestFailed = false;\n");
      out.write("\n");
      out.write("\n");
      out.write("    function displayText(){\n");
      out.write("        let row = document.getElementById(\"questTbl\").rows;\n");
      out.write("        let col = row[0].cells;\n");
      out.write("        col[0].innerHTML = '");
      out.print( quest.getStepDescription() );
      out.write("';\n");
      out.write("        let col1 = row[1].cells;\n");
      out.write("        if('");
      out.print(quest.getBtn2Result());
      out.write("' == 0 && '");
      out.print(quest.getBtn1Result());
      out.write("' == 0){\n");
      out.write("            document.getElementById('Btn1').style.visibility = 'hidden';\n");
      out.write("            document.getElementById(\"Btn2\").style.visibility = 'hidden';\n");
      out.write("            col1[0].innerHTML = '';\n");
      out.write("        }\n");
      out.write("        else {\n");
      out.write("            let lnk=document.getElementById('backLnk');\n");
      out.write("            //lnk.setAttribute(\"class\", \"disabled\");\n");
      out.write("            document.getElementById('backLnk').style.visibility = 'hidden';\n");
      out.write("            document.getElementById('Btn1').style.visibility = 'visible';\n");
      out.write("            document.getElementById('Btn2').style.visibility = 'visible';\n");
      out.write("            document.getElementById(\"Btn1\").innerHTML = '");
      out.print( quest.getBtn1Text() );
      out.write("'\n");
      out.write("            document.getElementById(\"Btn2\").innerHTML = '");
      out.print( quest.getBtn2Text() );
      out.write("'\n");
      out.write("        }\n");
      out.write("\n");
      out.write("    }\n");
      out.write("    function btn1Click(){\n");
      out.write("        let isQuestFailed = false;\n");
      out.write("        if ('");
      out.print(quest.getBtn1Result());
      out.write("' == 0) {\n");
      out.write("            isQuestFailed = true;\n");
      out.write("        }\n");
      out.write("        questResult(isQuestFailed);\n");
      out.write("    }\n");
      out.write("\n");
      out.write("\n");
      out.write("    function btn2Click(){\n");
      out.write("        let isQuestFailed = false;\n");
      out.write("        if ('");
      out.print(quest.getBtn2Result());
      out.write("' == 0) {\n");
      out.write("            isQuestFailed = true;\n");
      out.write("        }\n");
      out.write("        questResult(isQuestFailed);\n");
      out.write("    }\n");
      out.write("\n");
      out.write("function questResult (questResult){\n");
      out.write("    document.getElementById('Btn1').style.visibility = 'hidden';\n");
      out.write("    document.getElementById('Btn2').style.visibility = 'hidden';\n");
      out.write("    let row = document.getElementById(\"questTbl\").rows;\n");
      out.write("    let col = row[1].cells;\n");
      out.write("    if (questResult){\n");
      out.write("        col[0].innerHTML = '<br>You lose';\n");
      out.write("    } else {\n");
      out.write("        col[0].innerHTML = '<br>OK';\n");
      out.write("    }\n");
      out.write("}\n");
      out.write("</script>\n");
      out.write("\n");
      out.write("\n");
      out.write("</form>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
